/*{"mac":"1:2f0ce6dafc6e9350d10bdeec3039054024c3be13b5a4c9da3a36baaa1e9fb87b","created":"2013-06-24T17:55:23Z","version":"12364726","k":"1.5.6"}*/
/*
 * For font license information, see the CSS file loaded by this JavaScript.
 */
;(function(window,document,undefined){
var g=void 0,h=!0,l=null,m=!1;function n(a){return function(){return this[a]}}var aa=this;function ba(a,b){var c=a.split("."),e=aa;!(c[0]in e)&&e.execScript&&e.execScript("var "+c[0]);for(var d;c.length&&(d=c.shift());)!c.length&&b!==g?e[d]=b:e=e[d]?e[d]:e[d]={}}aa.ab=h;function da(a,b,c){return a.call.apply(a.bind,arguments)}
function ea(a,b,c){if(!a)throw Error();if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function p(a,b,c){p=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ea;return p.apply(l,arguments)}var fa=Date.now||function(){return+new Date};
function q(a,b){this.qa=a;this.aa=b||a;this.r=this.aa.document;this.ba=g}q.prototype.createElement=function(a,b,c){a=this.r.createElement(a);if(b)for(var e in b)if(b.hasOwnProperty(e))if("style"==e){var d=a,f=b[e];ga(this)?d.setAttribute("style",f):d.style.cssText=f}else a.setAttribute(e,b[e]);c&&a.appendChild(this.r.createTextNode(c));return a};function r(a,b,c){a=a.r.getElementsByTagName(b)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(c,a.lastChild)}
function ha(a,b){function c(){a.r.body?b():setTimeout(c,0)}c()}function s(a,b){for(var c=a.className.split(/\s+/),e=0,d=c.length;e<d;e++)if(c[e]==b)return;c.push(b);a.className=c.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function t(a,b){for(var c=a.className.split(/\s+/),e=[],d=0,f=c.length;d<f;d++)c[d]!=b&&e.push(c[d]);a.className=e.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}
function ka(a,b){for(var c=a.className.split(/\s+/),e=0,d=c.length;e<d;e++)if(c[e]==b)return h;return m}function ga(a){if(a.ba===g){var b=a.r.createElement("p");b.innerHTML='<a style="top:1px;">w</a>';a.ba=/top/.test(b.getElementsByTagName("a")[0].getAttribute("style"))}return a.ba}function la(a){var b=a.aa.location.protocol;"about:"==b&&(b=a.qa.location.protocol);return"https:"==b?"https:":"http:"}q.prototype.Z=function(){return this.aa.location.hostname||this.qa.location.hostname};
function ma(a,b,c){var e=a.r.getElementsByTagName("head")[0];if(e){var d=a.r.createElement("script");d.src=b;var f=m;d.onload=d.onreadystatechange=function(){if(!f&&(!this.readyState||"loaded"==this.readyState||"complete"==this.readyState))f=h,c&&c(),d.onload=d.onreadystatechange=l,"HEAD"==d.parentNode.tagName&&e.removeChild(d)};e.appendChild(d)}}function u(a,b,c){this.Za=a;this.ea=b;this.Ya=c}ba("internalWebfont.BrowserInfo",u);u.prototype.Ka=n("Za");u.prototype.hasWebFontSupport=u.prototype.Ka;
u.prototype.La=n("ea");u.prototype.hasWebKitFallbackBug=u.prototype.La;u.prototype.Ma=n("Ya");u.prototype.hasWebKitMetricsBug=u.prototype.Ma;function v(a,b,c,e){this.e=a!=l?a:l;this.k=b!=l?b:l;this.A=c!=l?c:l;this.h=e!=l?e:l}var na=/^([0-9]+)(?:[\._-]([0-9]+))?(?:[\._-]([0-9]+))?(?:[\._+-]?(.*))?$/;function w(a){return a.e!==l}function x(a,b){return a.e>b.e||a.e===b.e&&a.k>b.k||a.e===b.e&&a.k===b.k&&a.A>b.A?1:a.e<b.e||a.e===b.e&&a.k<b.k||a.e===b.e&&a.k===b.k&&a.A<b.A?-1:0}
function y(a,b){return-1===x(a,b)}function z(a,b){return 0===x(a,b)||1===x(a,b)}function B(a,b){return 0===x(a,b)}v.prototype.toString=function(){return[this.e,this.k||"",this.A||"",this.h||""].join("")};function C(a){a=na.exec(a);var b=l,c=l,e=l,d=l;a&&(a[1]!==l&&a[1]&&(b=parseInt(a[1],10)),a[2]!==l&&a[2]&&(c=parseInt(a[2],10)),a[3]!==l&&a[3]&&(e=parseInt(a[3],10)),a[4]!==l&&a[4]&&(d=/^[0-9]+$/.test(a[4])?parseInt(a[4],10):a[4]));return new v(b,c,e,d)}
function D(a,b,c,e,d,f,k,j,A,ca,F){this.z=a;this.Xa=b;this.Wa=c;this.ka=e;this.Aa=d;this.za=f;this.ta=k;this.Sa=j;this.Ra=A;this.ja=ca;this.s=F}ba("internalWebfont.UserAgent",D);D.prototype.getName=n("z");D.prototype.getName=D.prototype.getName;D.prototype.Ja=n("Wa");D.prototype.getVersion=D.prototype.Ja;D.prototype.Fa=n("ka");D.prototype.getEngine=D.prototype.Fa;D.prototype.Ga=n("za");D.prototype.getEngineVersion=D.prototype.Ga;D.prototype.Ha=n("ta");D.prototype.getPlatform=D.prototype.Ha;
D.prototype.Ia=n("Ra");D.prototype.getPlatformVersion=D.prototype.Ia;D.prototype.Ea=n("ja");D.prototype.getDocumentMode=D.prototype.Ea;D.prototype.Da=n("s");D.prototype.getBrowserInfo=D.prototype.Da;function oa(a,b){this.c=a;this.K=b}var pa=new D("Unknown",new v,"Unknown","Unknown",new v,"Unknown","Unknown",new v,"Unknown",g,new u(m,m,m));
oa.prototype.parse=function(){var a;if(-1!=this.c.indexOf("MSIE")){a=G(this);var b=I(this),c=C(b),e=J(this.c,/MSIE ([\d\w\.]+)/,1),d=C(e);a=new D("MSIE",d,e,"MSIE",d,e,a,c,b,K(this.K),new u("Windows"==a&&6<=d.e||"Windows Phone"==a&&8<=c.e,m,m))}else if(-1!=this.c.indexOf("Opera"))a:{a="Unknown";var b=J(this.c,/Presto\/([\d\w\.]+)/,1),c=C(b),e=I(this),d=C(e),f=K(this.K);w(c)?a="Presto":(-1!=this.c.indexOf("Gecko")&&(a="Gecko"),b=J(this.c,/rv:([^\)]+)/,1),c=C(b));if(-1!=this.c.indexOf("Opera Mini/")){var k=
J(this.c,/Opera Mini\/([\d\.]+)/,1),j=C(k);a=new D("OperaMini",j,k,a,c,b,G(this),d,e,f,new u(m,m,m))}else{if(-1!=this.c.indexOf("Version/")&&(k=J(this.c,/Version\/([\d\.]+)/,1),j=C(k),w(j))){a=new D("Opera",j,k,a,c,b,G(this),d,e,f,new u(10<=j.e,m,m));break a}k=J(this.c,/Opera[\/ ]([\d\.]+)/,1);j=C(k);a=w(j)?new D("Opera",j,k,a,c,b,G(this),d,e,f,new u(10<=j.e,m,m)):new D("Opera",new v,"Unknown",a,c,b,G(this),d,e,f,new u(m,m,m))}}else/AppleWeb(K|k)it/.test(this.c)?(a=G(this),b=I(this),c=C(b),e=J(this.c,
/AppleWeb(?:K|k)it\/([\d\.\+]+)/,1),d=C(e),f="Unknown",k=new v,j=m,-1!=this.c.indexOf("Chrome")||-1!=this.c.indexOf("CrMo")||-1!=this.c.indexOf("CriOS")?f="Chrome":/Silk\/\d/.test(this.c)?f="Silk":"BlackBerry"==a||"Android"==a?f="BuiltinBrowser":-1!=this.c.indexOf("Safari")?f="Safari":-1!=this.c.indexOf("AdobeAIR")&&(f="AdobeAIR"),"BuiltinBrowser"==f?k=new v:"Silk"==f?k=C(J(this.c,/Silk\/([\d\._]+)/,1)):"Chrome"==f?k=C(J(this.c,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2)):-1!=this.c.indexOf("Version/")?k=
C(J(this.c,/Version\/([\d\.\w]+)/,1)):"AdobeAIR"==f&&(k=C(J(this.c,/AdobeAIR\/([\d\.]+)/,1))),j="AdobeAIR"==f?2<k.e||2==k.e&&5<=k.k:"BlackBerry"==a?10<=c.e:"Android"==a?2<c.e||2==c.e&&1<c.k:526<=d.e||525<=d.e&&13<=d.k,a=new D(f,k,"Unknown","AppleWebKit",d,e,a,c,b,K(this.K),new u(j,536>d.e||536==d.e&&11>d.k,"iPhone"==a||"iPad"==a||"iPod"==a||"Macintosh"==a))):-1!=this.c.indexOf("Gecko")?(a="Unknown",b=new v,c="Unknown",e=I(this),d=C(e),f=m,-1!=this.c.indexOf("Firefox")?(a="Firefox",c=J(this.c,/Firefox\/([\d\w\.]+)/,
1),b=C(c),f=3<=b.e&&5<=b.k):-1!=this.c.indexOf("Mozilla")&&(a="Mozilla"),k=J(this.c,/rv:([^\)]+)/,1),j=C(k),f||(f=1<j.e||1==j.e&&9<j.k||1==j.e&&9==j.k&&2<=j.A||k.match(/1\.9\.1b[123]/)!=l||k.match(/1\.9\.1\.[\d\.]+/)!=l),a=new D(a,b,c,"Gecko",j,k,G(this),d,e,K(this.K),new u(f,m,m))):a=pa;return a};
function G(a){var b=J(a.c,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=b)return/BB\d{2}/.test(b)&&(b="BlackBerry"),b;a=J(a.c,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS)/,1);return""!=a?("Mac_PowerPC"==a&&(a="Macintosh"),a):"Unknown"}
function I(a){var b=J(a.c,/(OS X|Windows NT|Android) ([^;)]+)/,2);if(b||(b=J(a.c,/Windows Phone( OS)? ([^;)]+)/,2))||(b=J(a.c,/(iPhone )?OS ([\d_]+)/,2)))return b;if(b=J(a.c,/(?:Linux|CrOS) ([^;)]+)/,1))for(var b=b.split(/\s/),c=0;c<b.length;c+=1)if(/^[\d\._]+$/.test(b[c]))return b[c];return(a=J(a.c,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}function J(a,b,c){return(a=a.match(b))&&a[c]?a[c]:""}function K(a){if(a.documentMode)return a.documentMode}function qa(a){this.Pa=a||"-"}
qa.prototype.h=function(a){for(var b=[],c=0;c<arguments.length;c++)b.push(arguments[c].replace(/[\W_]+/g,"").toLowerCase());return b.join(this.Pa)};function ra(a,b,c){this.g=a;this.j=b;this.T=c;this.n="wf";this.m=new qa("-")}function sa(a){t(a.j,a.m.h(a.n,"loading"));ka(a.j,a.m.h(a.n,"active"))||s(a.j,a.m.h(a.n,"inactive"));L(a,"inactive")}function L(a,b,c){if(a.T[b])if(c)a.T[b](c.getName(),M(c));else a.T[b]()}
function N(a,b){this.z=a;this.fa=4;this.O="n";var c=(b||"n4").match(/^([nio])([1-9])$/i);c&&(this.O=c[1],this.fa=parseInt(c[2],10))}N.prototype.getName=n("z");function M(a){return a.O+a.fa}function O(a,b){this.g=a;this.I=b;this.u=this.g.createElement("span",{"aria-hidden":"true"},this.I)}
function ta(a,b){var c=a.u,e;e=[];for(var d=b.z.split(/,\s*/),f=0;f<d.length;f++){var k=d[f].replace(/['"]/g,"");-1==k.indexOf(" ")?e.push(k):e.push("'"+k+"'")}e=e.join(",");d="normal";f=b.fa+"00";"o"===b.O?d="oblique":"i"===b.O&&(d="italic");e="position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+e+";"+("font-style:"+d+";font-weight:"+f+";");ga(a.g)?c.setAttribute("style",e):c.style.cssText=
e}function ua(a){r(a.g,"body",a.u)}O.prototype.remove=function(){var a=this.u;a.parentNode&&a.parentNode.removeChild(a)};function va(a,b,c,e,d,f,k,j){this.ga=a;this.Oa=b;this.g=c;this.t=e;this.I=j||"BESbswy";this.s=d;this.J={};this.ca=f||5E3;this.ra=k||l;this.H=this.G=l;a=new O(this.g,this.I);ua(a);for(var A in Q)Q.hasOwnProperty(A)&&(ta(a,new N(Q[A],M(this.t))),this.J[Q[A]]=a.u.offsetWidth);a.remove()}var Q={eb:"serif",cb:"sans-serif",bb:"monospace"};
va.prototype.start=function(){this.G=new O(this.g,this.I);ua(this.G);this.H=new O(this.g,this.I);ua(this.H);this.Ua=fa();ta(this.G,new N(this.t.getName()+",serif",M(this.t)));ta(this.H,new N(this.t.getName()+",sans-serif",M(this.t)));wa(this)};function xa(a,b,c){for(var e in Q)if(Q.hasOwnProperty(e)&&b===a.J[Q[e]]&&c===a.J[Q[e]])return h;return m}
function wa(a){var b=a.G.u.offsetWidth,c=a.H.u.offsetWidth;b===a.J.serif&&c===a.J["sans-serif"]||a.s.ea&&xa(a,b,c)?fa()-a.Ua>=a.ca?a.s.ea&&xa(a,b,c)&&(a.ra===l||a.ra.hasOwnProperty(a.t.getName()))?ya(a,a.ga):ya(a,a.Oa):setTimeout(p(function(){wa(this)},a),25):ya(a,a.ga)}function ya(a,b){a.G.remove();a.H.remove();b(a.t)}function R(a,b,c,e){this.g=b;this.v=c;this.W=0;this.va=this.pa=m;this.ca=e;this.s=a.s}
R.prototype.da=function(a,b,c,e){if(0===a.length&&e)sa(this.v);else{this.W+=a.length;e&&(this.pa=e);for(e=0;e<a.length;e++){var d=a[e],f=b[d.getName()],k=this.v,j=d;s(k.j,k.m.h(k.n,j.getName(),M(j).toString(),"loading"));L(k,"fontloading",j);(new va(p(this.Ba,this),p(this.Ca,this),this.g,d,this.s,this.ca,c,f)).start()}}};
R.prototype.Ba=function(a){var b=this.v;t(b.j,b.m.h(b.n,a.getName(),M(a).toString(),"loading"));t(b.j,b.m.h(b.n,a.getName(),M(a).toString(),"inactive"));s(b.j,b.m.h(b.n,a.getName(),M(a).toString(),"active"));L(b,"fontactive",a);this.va=h;za(this)};R.prototype.Ca=function(a){var b=this.v;t(b.j,b.m.h(b.n,a.getName(),M(a).toString(),"loading"));ka(b.j,b.m.h(b.n,a.getName(),M(a).toString(),"active"))||s(b.j,b.m.h(b.n,a.getName(),M(a).toString(),"inactive"));L(b,"fontinactive",a);za(this)};
function za(a){0==--a.W&&a.pa&&(a.va?(a=a.v,t(a.j,a.m.h(a.n,"loading")),t(a.j,a.m.h(a.n,"inactive")),s(a.j,a.m.h(a.n,"active")),L(a,"active")):sa(a.v))}function Aa(a,b){this.Ta=a;this.ia=b}function Ba(a){for(var b=a.Ta.join(","),c=[],e=0;e<a.ia.length;e++){var d=a.ia[e];c.push(d.name+":"+d.value+";")}return b+"{"+c.join("")+"}"}function Ca(a){this.g=a}Ca.prototype.toString=function(){return encodeURIComponent(this.g.Z?this.g.Z():document.location.hostname)};function Da(a,b){this.q=a;this.l=b}
Da.prototype.toString=function(){for(var a=[],b=0;b<this.l.length;b++)for(var c=this.l[b],e=c.w(),c=c.w(this.q),d=0;d<e.length;d++){var f;a:{for(f=0;f<c.length;f++)if(e[d]===c[f]){f=h;break a}f=m}a.push(f?1:0)}a=a.join("");a=a.replace(/^0+/,"");b=[];for(e=a.length;0<e;e-=4)c=a.slice(0>e-4?0:e-4,e),b.unshift(parseInt(c,2).toString(16));return b.join("")};function Ea(a,b,c){this.g=a;this.q=b;this.l=c}function S(a){this.Va=a}
S.prototype.h=function(a,b){var c=b||{},e=this.Va.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,b,e){return e&&c[b]?"/"+c[b].join("/"):c[b]||""});e.match(/^\/\//)&&(e=(a?"https:":"http:")+e);return e.replace(/\/*\?*($|\?)/,"$1")};function T(a,b,c,e){this.F=a;this.L=b;this.Na=c;this.fb=e;this.ma={};this.la={}}T.prototype.w=function(a){return a?(this.ma[a.P]||this.L).slice(0):this.L.slice(0)};T.prototype.da=function(a,b,c){var e=[],d={};Fa(this,b,e,d);a(e,d,c)};
function Fa(a,b,c,e){c.push(a.F);e[a.F]=a.w(b);a=a.la[b.P]||[];for(b=0;b<a.length;b++){for(var d=a[b],f=d.F,k=m,j=0;j<c.length;j++)c[j]==f&&(k=h);k||(c.push(f),e[f]=d.w())}}function Ga(a,b){this.F=a;this.L=b}Ga.prototype.w=n("L");function Ia(){this.xa=this.$a=this.p=this.M=this.N=h}function U(a,b,c){this.Na=a;this.P=b;this.oa=c}function V(a){Ja.S.push(a)}function W(a){this.g=a;this.ya=this.q=this.c=this.R=l;this.l=[];this.D=[];this.wa=this.X=this.U=this.V=l}
function Ka(a,b){a.c=b;if(a.R){var c;a:{c=a.R;for(var e=a.c,d=a.ya,f=0;f<c.S.length;f++){var k=c.S[f],j=d;j||(j=new Ia);if(k.oa&&k.oa(e.getName(),e.Xa,e.ka,e.Aa,e.ta,e.Sa,e.ja,j)){c=k;break a}}c=l}a.q=c}}W.prototype.supportsConfiguredBrowser=function(){return!!this.q};
W.prototype.init=function(){if(0<this.D.length){for(var a=[],b=0;b<this.D.length;b++)a.push(Ba(this.D[b]));var b=this.g,a=a.join(""),c=this.g.r.createElement("style");c.setAttribute("type","text/css");c.styleSheet?c.styleSheet.cssText=a:c.appendChild(document.createTextNode(a));r(b,"head",c)}};
W.prototype.load=function(a,b){var c=this.q.P;if(this.X){var e;e=this.X;var d=e.B[c];e=d?La(e,d):l;for(d=0;d<this.l.length;d++){for(var f=this.l[d],k=this.q,j=e,A=[],ca=f.F.split(",")[0].replace(/"|'/g,""),F=f.w(),P=A,E=g,H=[],Ha={},ia=0;ia<F.length;ia++)E=F[ia],0<E.length&&!Ha[E]&&(Ha[E]=h,H.push(E));F=H;j=j.ua?j.ua(ca,F,P):F;k=k.P;f.ma[k]=j;f.la[k]=A}}if(this.V){e=[];if(this.U){e=new Ea(this.g,this.q,this.l);d=[];f=this.U.C[c]||[];for(A=0;A<f.length;A++){a:switch(f[A]){case "observeddomain":k=new Ca(e.g);
break a;case "fontmask":k=new Da(e.q,e.l);break a;default:k=l}k&&d.push(k)}e=d}d=[];for(f=0;f<e.length;f++)d.push(e[f].toString());c=this.V.h("https:"===la(this.g),{format:c,extras:d});r(this.g,"head",this.g.createElement("link",{rel:"stylesheet",href:c}))}if(a){var ja=this,Wa=this.q;ha(this.g,function(){for(var c=0;c<ja.l.length;c++)ja.l[c].da(a,Wa,b&&c==ja.l.length-1)})}};W.prototype.collectFontFamilies=function(a,b){for(var c=0;c<this.l.length;c++)Fa(this.l[c],this.q,a,b)};
W.prototype.performOptionalActions=function(){if(this.$){var a=this,b=this.c,c=this.g;ha(this.g,function(){var e=a.$;if(e.sa){var d=window.__adobewebfontsappname__,d=d?d.toString().substr(0,20):"",e=e.sa.h("https:"===la(c),{host:encodeURIComponent(c.Z()),app:encodeURIComponent(d),_:(+new Date).toString()}),f=new Image(1,1);f.src=e;f.onload=function(){f.onload=l}}e=a.$;e.ha&&(e=e.ha.h(b,c),r(c,"body",e))})}};function Ma(a,b,c,e){this.Qa=a;this.g=b;this.c=c;this.j=e;this.o=[]}Ma.prototype.Q=function(a){this.o.push(a)};
Ma.prototype.load=function(a,b){var c=a,e=b||{};if("string"==typeof c)c=[c];else if(!c||!c.length)e=c||{},c=[];if(c.length)for(var d=this,f=c.length,k=0;k<c.length;k++){var j=this.Qa.h("https:"===la(this.g),{id:encodeURIComponent(c[k])});ma(this.g,j,function(){0==--f&&Na(d,e)})}else Na(this,e)};
function Na(a,b){if(0!=a.o.length){for(var c=new ra(a.g,a.j,b),e=m,d=0;d<a.o.length;d++)a.o[d].init(),e=e||a.o[d].supportsConfiguredBrowser();if(e){s(c.j,c.m.h(c.n,"loading"));L(c,"loading");for(var f=new R(a.c,a.g,c),c=function(a,b,c){for(var d=[],e=0;e<a.length;e+=1){var P=a[e];if(b[P])for(var E=b[P],H=0;H<E.length;H+=1)d.push(new N(P,E[H]));else d.push(new N(P))}f.da(d,{},l,c)},e=0;e<a.o.length;e++)d=a.o[e],d.supportsConfiguredBrowser()&&(d.load(c,e==a.o.length-1),d.performOptionalActions(window))}else sa(c);
a.o=[]}}function Oa(a){this.na=a;this.o=[]}Oa.prototype.Q=function(a){this.o.push(a)};Oa.prototype.load=function(){var a=this.na.__webfonttypekitmodule__;if(a)for(var b=0;b<this.o.length;b++){var c=this.o[b],e=a[c.wa];e&&e(function(a,b,e){a=[];b={};var j=(new oa(navigator.userAgent,document)).parse();Ka(c,j);c.supportsConfiguredBrowser()&&(c.init(),c.load(l),c.collectFontFamilies(a,b),c.performOptionalActions(window));e(c.supportsConfiguredBrowser(),a,b)})}};function Pa(a,b){this.z=a;this.ua=b}
Pa.prototype.getName=n("z");function Qa(a){var b=X;La(b,a.getName())||b.Y.push(a)}function La(a,b){for(var c=0;c<a.Y.length;c++){var e=a.Y[c];if(b===e.getName())return e}return l}var Ja=new function(){this.S=[]};V(new U("air-linux-win","a",function(a,b,c,e,d,f){c=m||"Windows"==d&&!w(f);return!c&&!("Ubuntu"==d||"Linux"==d)?m:"AdobeAIR"==a?z(b,new v(2,5)):m}));
V(new U("air-osx","b",function(a,b,c,e,d,f){c=m||"Macintosh"==d&&z(f,new v(10,4))||"Macintosh"==d&&!w(f);return!c?m:"AdobeAIR"==a?z(b,new v(2,5)):m}));V(new U("builtin-android2to3-android4plus","a",function(a,b,c,e,d,f,k,j){b=(b=m||j.p&&"Android"==d&&z(f,new v(2,2))&&y(f,new v(3,1)))||j.p&&"Android"==d&&z(f,new v(4,1));return!b?m:"BuiltinBrowser"==a}));
V(new U("builtin-android3to4","f",function(a,b,c,e,d,f,k,j){b=m||j.p&&"Android"==d&&z(f,new v(3,1))&&y(f,new v(4,1));return!b?m:"BuiltinBrowser"==a}));V(new U("builtin-bb10plus","d",function(a,b,c,e,d,f,k,j){b=m||j.xa&&z(f,new v(10));return!b?m:"BuiltinBrowser"==a}));
V(new U("chrome4to5-linux-osx-win2003-win7plus-winvista-winxp","a",function(a,b,c,e,d,f){c=(c=(c=(c=(c=m||"Windows"==d&&B(f,new v(5,1)))||"Windows"==d&&B(f,new v(5,2)))||"Windows"==d&&B(f,new v(6,0)))||"Windows"==d&&z(f,new v(6,1)))||"Macintosh"==d&&z(f,new v(10,4))||"Macintosh"==d&&!w(f);return!c&&!("Ubuntu"==d||"Linux"==d)?m:"Chrome"==a&&(1===x(b,new v(4,0,249))&&y(b,new v(6))||B(b,new v(4,0,249))&&(b.h===l||4<=b.h))?h:m}));
V(new U("chrome6plus-androidany-chromeos-ipad5plus-iphone5plus-linux-osx-win2003-win7plus-winvista-winxp","d",function(a,b,c,e,d,f,k,j){a=(c=(c=(c=(c=(c=(c=(c=(c=(c=m||"Windows"==d&&B(f,new v(5,1)))||"Windows"==d&&B(f,new v(5,2)))||"Windows"==d&&B(f,new v(6,0)))||"Windows"==d&&z(f,new v(6,1)))||"Macintosh"==d&&z(f,new v(10,4))||"Macintosh"==d&&!w(f))||("Ubuntu"==d||"Linux"==d)||j.p&&"Android"==d)||"CrOS"==d)||(j.M&&"iPad"==d?z(f,new v(5)):m))||(j.N&&("iPhone"==d||"iPod"==d)?z(f,new v(5)):m))?"Chrome"==
a?z(b,new v(6)):g:m;return a}));V(new U("chrome6plus-ipad4-iphone4","a",function(a,b,c,e,d,f,k,j){a=(c=(c=m||(j.M&&"iPad"==d?z(f,new v(4,2))&&y(f,new v(5)):m))||(j.N&&("iPhone"==d||"iPod"==d)?z(f,new v(4,2))&&y(f,new v(5)):m))?"Chrome"==a?z(b,new v(6)):g:m;return a}));
V(new U("ff35-linux-win2003-win7plus-winvista-winxp","a",function(a,b,c,e,d,f){a=(a=(a=(a=m||"Windows"==d&&B(f,new v(5,1)))||"Windows"==d&&B(f,new v(5,2)))||"Windows"==d&&B(f,new v(6,0)))||"Windows"==d&&z(f,new v(6,1));return!a&&!("Ubuntu"==d||"Linux"==d)?m:"Gecko"==c?B(e,new v(1,9,1))&&!/^b[1-3]$/.test(e.h||""):m}));V(new U("ff35-osx","b",function(a,b,c,e,d,f){a=m||"Macintosh"==d&&z(f,new v(10,4))||"Macintosh"==d&&!w(f);return!a?m:"Gecko"==c?B(e,new v(1,9,1))&&!/^b[1-3]$/.test(e.h||""):m}));
V(new U("ff36plus-androidany-linux-osx-win2003-win7plus-winvista-winxp","d",function(a,b,c,e,d,f,k,j){a=(a=(a=(a=(a=(a=m||"Windows"==d&&B(f,new v(5,1)))||"Windows"==d&&B(f,new v(5,2)))||"Windows"==d&&B(f,new v(6,0)))||"Windows"==d&&z(f,new v(6,1)))||"Macintosh"==d&&z(f,new v(10,4))||"Macintosh"==d&&!w(f))||("Ubuntu"==d||"Linux"==d)||j.p&&"Android"==d;return!a?m:"Gecko"==c?1===x(e,new v(1,9,1)):m}));
V(new U("ie6to8-win2003-win7plus-winvista-winxp","i",function(a,b,c,e,d,f,k){a=(c=(c=(c=(c=m||"Windows"==d&&B(f,new v(5,1)))||"Windows"==d&&B(f,new v(5,2)))||"Windows"==d&&B(f,new v(6,0)))||"Windows"==d&&z(f,new v(6,1)))?"MSIE"==a?z(b,new v(6,0))&&(k===g||9>k):g:m;return a}));V(new U("ie9plus-win7plus-winvista","d",function(a,b,c,e,d,f,k){a=(b=(b=m||"Windows"==d&&z(f,new v(6,1)))||"Windows"==d&&B(f,new v(6,0)))?"MSIE"==a?9<=k:g:m;return a}));
V(new U("ieany-winphone8plus","d",function(a,b,c,e,d,f,k,j){b=m||j.$a&&"Windows Phone"==d&&z(f,new v(8));return!b?m:"MSIE"==a}));V(new U("opera10-linux-win2003-win7plus-winvista-winxp","a",function(a,b,c,e,d,f){c=(c=(c=(c=m||"Windows"==d&&B(f,new v(5,1)))||"Windows"==d&&B(f,new v(5,2)))||"Windows"==d&&B(f,new v(6,0)))||"Windows"==d&&z(f,new v(6,1));return!c&&!("Ubuntu"==d||"Linux"==d)?m:"Opera"==a?z(b,new v(10,54))&&y(b,new v(11,10)):m}));
V(new U("opera10-osx","b",function(a,b,c,e,d,f){c=m||"Macintosh"==d&&z(f,new v(10,4))||"Macintosh"==d&&!w(f);return!c?m:"Opera"==a?z(b,new v(10,54))&&y(b,new v(11,10)):m}));
V(new U("opera11plus-androidany-linux-osx-win2003-win7plus-winvista-winxp","d",function(a,b,c,e,d,f,k,j){c=(c=(c=(c=(c=(c=m||"Windows"==d&&B(f,new v(5,1)))||"Windows"==d&&B(f,new v(5,2)))||"Windows"==d&&B(f,new v(6,0)))||"Windows"==d&&z(f,new v(6,1)))||"Macintosh"==d&&z(f,new v(10,4))||"Macintosh"==d&&!w(f))||("Ubuntu"==d||"Linux"==d)||j.p&&"Android"==d;return!c?m:"Opera"==a?z(b,new v(11,10)):m}));
V(new U("safari3to5-osx","b",function(a,b,c,e,d,f){b=m||"Macintosh"==d&&z(f,new v(10,4))||"Macintosh"==d&&!w(f);return!b?m:"Safari"==a&&"AppleWebKit"==c?z(e,new v(525,13))&&y(e,new v(534,50)):m}));V(new U("safari3to5-win2003-win7plus-winvista-winxp","a",function(a,b,c,e,d,f){b=(b=(b=(b=m||"Windows"==d&&B(f,new v(5,1)))||"Windows"==d&&B(f,new v(5,2)))||"Windows"==d&&B(f,new v(6,0)))||"Windows"==d&&z(f,new v(6,1));return!b?m:"Safari"==a&&"AppleWebKit"==c?z(e,new v(525,13))&&y(e,new v(534,50)):m}));
V(new U("safari5plus-osx-win2003-win7plus-winvista-winxp","d",function(a,b,c,e,d,f){b=(b=(b=(b=(b=m||"Windows"==d&&B(f,new v(5,1)))||"Windows"==d&&B(f,new v(5,2)))||"Windows"==d&&B(f,new v(6,0)))||"Windows"==d&&z(f,new v(6,1)))||"Macintosh"==d&&z(f,new v(10,4))||"Macintosh"==d&&!w(f);return!b?m:"Safari"==a&&"AppleWebKit"==c?z(e,new v(534,50)):m}));
V(new U("safariany-ipad4-iphone4","a",function(a,b,c,e,d,f,k,j){b=(b=m||(j.M&&"iPad"==d?z(f,new v(4,2))&&y(f,new v(5)):m))||(j.N&&("iPhone"==d||"iPod"==d)?z(f,new v(4,2))&&y(f,new v(5)):m);return!b?m:"Safari"==a&&"AppleWebKit"==c||"Unknown"==a&&"AppleWebKit"==c&&("iPhone"==d||"iPad"==d)?h:m}));
V(new U("safariany-ipad5plus-iphone5plus","d",function(a,b,c,e,d,f,k,j){b=(b=m||(j.M&&"iPad"==d?z(f,new v(5)):m))||(j.N&&("iPhone"==d||"iPod"==d)?z(f,new v(5)):m);return!b?m:"Safari"==a&&"AppleWebKit"==c||"Unknown"==a&&"AppleWebKit"==c&&("iPhone"==d||"iPad"==d)?h:m}));V(new U("silk1to2-android2to3-osx","a",function(a,b,c,e,d,f,k,j){c=(c=m||j.p&&"Android"==d&&z(f,new v(2,2))&&y(f,new v(3,1)))||"Macintosh"==d&&z(f,new v(10,4))||"Macintosh"==d&&!w(f);return!c?m:j.p&&"Silk"==a?y(b,new v(2)):m}));
V(new U("silk2plus-android3to4-linux","f",function(a,b,c,e,d,f,k,j){c=m||j.p&&"Android"==d&&z(f,new v(3,1))&&y(f,new v(4,1));return!c&&!("Ubuntu"==d||"Linux"==d)?m:j.p&&"Silk"==a?z(b,new v(2)):m}));V(new U("silk2plus-android4plus","a",function(a,b,c,e,d,f,k,j){c=m||j.p&&"Android"==d&&z(f,new v(4,1));return!c?m:j.p&&"Silk"==a?z(b,new v(2)):m}));var X=new function(){this.Y=[];this.B={}};Qa(new Pa("AllFonts",function(a,b){return b}));
Qa(new Pa("DefaultFourFontsWithSingleFvdFamilies",function(a,b,c){for(var e=0;e<b.length;e++){var d=b[e],f=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+d;c.push(new Ga(f,[d]))}a={};for(d=0;d<b.length;d++)c=b[d],e=c.charAt(1),(a[e]||(a[e]=[])).push(c);c=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];e=[];for(d=0;d<c.length;d++)for(var f=c[d],k=0;k<f.length;k++){var j=f[k];if(a[j]){e=e.concat(a[j]);break}}c=e;e={};a=[];for(d=0;d<c.length;d++)f=c[d],e[f]||(e[f]=h,a.push(f));c=[];for(e=0;e<b.length;e++){d=b[e];
for(f=0;f<a.length;f++)k=a[f],k==d&&c.push(k)}return c}));X.B.a="AllFonts";X.B.b="AllFonts";X.B.d="AllFonts";X.B.f="AllFonts";X.B.i="DefaultFourFontsWithSingleFvdFamilies";var Y=new function(){this.C={}};Y.C.a=[];Y.C.b=[];Y.C.d=[];Y.C.f=["observeddomain"];Y.C.i=["observeddomain","fontmask"];var Ra=(new oa(navigator.userAgent,document)).parse();window.Typekit||(window.Typekit={});
if(!window.Typekit.load){var Z=new Ma(new S("//typeface.nytimes.com/{id}.js"),new q(window),Ra,document.documentElement),Sa=new Oa(window);window.Typekit.load=function(){Z.load.apply(Z,arguments)};window.Typekit.addKit=function(){Z.Q.apply(Z,arguments)}}var Ta=l,Ua,$,Ta=new S("//p.typekit.net/p.gif?a=343068&f=387.389.391.405&h={host}&ht=sh&k=ucf6rje&s=1&_={_}");Ua=new function(){var a=Ta;this.ha=l;this.sa=a};$=new W(new q(window));$.wa="ucf6rje";$.V=new S("//typeface.nytimes.com/k/ucf6rje-{format}.css?3bb2a6e53c9684ffdc9a9bf51d5b2a62c96de82d85c740a9a6cf00238e596d67ac7c2b14ba9b9f3919e827a2e7ef3e36b75992729d296aa08166934a9d81d99757cdcc181cb2029220087be2f26dfa73c3552ac69a1816934b005dad6c70ce824d19f1b23f9e9f4a8aca315346dc174eead7faf6e5808462e1d21544f9e91264d9e7be7a30955612a3");
$.$=Ua;$.l.push(new T("nyt-franklin",["n3","n5","n7"]));$.l.push(new T("nyt-cheltenham",["n4"]));$.D.push(new Aa([".tk-nyt-franklin"],[{name:"font-family",value:'"nyt-franklin",sans-serif'}]));$.D.push(new Aa([".tk-nyt-cheltenham"],[{name:"font-family",value:'"nyt-cheltenham",sans-serif'}]));$.R=Ja;$.U=Y;$.X=X;var Va;if(Va=Sa)Va=!!Sa.na.__webfonttypekitmodule__;Va?(Sa.Q($),Sa.load()):(Ka($,Ra),window.Typekit.addKit($));
})(this,document);